module.exports = {
    DASHBOARD: 'icon-home4',
    USER: 'icon-user',
    USER_PROFILE: 'icon-user-tie',
    USERS: 'icon-users2',
    IMAGE: 'icon-images2',
    PASSWORD: 'icon-lock2',
    LOGOUT: 'icon-switch2',
    ADD: 'icon-plus22',
    EDIT: 'icon-pencil7',
    REMOVE: 'icon-trash',
    APPROVED: 'fa fa-check',
    REJECTED: 'fa fa-times',
    SAVE: 'fa fa-save',
    BACK: 'fa fa-chevron-left',
    CHECKED: 'fa fa-check',
    REVIEW: 'fa fa-eye',
    ERROR: 'fa fa-warning',
    SEARCH: 'fa fa-search-plus',
    SELECT_IMAGE: 'fa fa-check',
    TAG: 'fa fa-tags',
    NLP: 'icon-yin-yang'
};
