module.exports = {
    ensureArray: require('./src/ensureArray'),
    formatCurrency: require('./src/formatCurrency'),
    getObjectValues: require('./src/getObjectValues'),
    getUploadFileName: require('./src/getUploadFileName'),
    isValidJsonString: require('./src/isValidJsonString'),
    loopArray: require('./src/loopArray'),
    newError: require('./src/newError'),
    normalizeSpace: require('./src/normalizeSpace'),
    removeTone: require('./src/removeTone'),
    toCamelCase: require('./src/toCamelCase'),
    toKebabCase: require('./src/toKebabCase'),
    toPascalCase: require('./src/toPascalCase'),
    toSentenceCase: require('./src/toSentenceCase'),
    toSnakeCase: require('./src/toSnakeCase'),
    toTitleCase: require('./src/toTitleCase'),
};
