module.exports = {
    cleanFolder: require('./src/cleanFolder'),
    ensureArray: require('./src/ensureArray'),
    formatCurrency: require('./src/formatCurrency'),
    getExcelSheetData: require('./src/getExcelSheetData'),
    getFileList: require('./src/getFileList'),
    getFolderList: require('./src/getFolderList'),
    getLogger: require('./src/getLogger'),
    getObjectValues: require('./src/getObjectValues'),
    getUploadFileName: require('./src/getUploadFileName'),
    getWinstonLogger: require('./src/getWinstonLogger'),
    isValidJsonString: require('./src/isValidJsonString'),
    loopArray: require('./src/loopArray'),
    newError: require('./src/newError'),
    normalizeSpace: require('./src/normalizeSpace'),
    removeTone: require('./src/removeTone'),
    resolvePath: require('./src/resolvePath'),
    toCamelCase: require('./src/toCamelCase'),
    toKebabCase: require('./src/toKebabCase'),
    toPascalCase: require('./src/toPascalCase'),
    toSentenceCase: require('./src/toSentenceCase'),
    toSnakeCase: require('./src/toSnakeCase'),
    toTitleCase: require('./src/toTitleCase'),
    writeExcel: require('./src/writeExcel'),
    writeExcelToFile: require('./src/writeExcelToFile'),
};
