module.exports = {    ensureArray: require('./src/ensureArray'),
    formatNumber: require('./src/formatNumber'),
    getObjectValues: require('./src/getObjectValues'),
    getUploadFileName: require('./src/getUploadFileName'),
    isValidJsonString: require('./src/isValidJsonString'),
    loopArray: require('./src/loopArray'),
    newError: require('./src/newError'),
    normalizeSpace: require('./src/normalizeSpace'),
    range: require('./src/range'),
    regex: require('./src/regex'),
    removeTone: require('./src/removeTone'),
    toCamelCase: require('./src/toCamelCase'),
    toKebabCase: require('./src/toKebabCase'),
    toPascalCase: require('./src/toPascalCase'),
    toSentenceCase: require('./src/toSentenceCase'),
    toSnakeCase: require('./src/toSnakeCase'),
    toTitleCase: require('./src/toTitleCase'),
    tryParseJson: require('./src/tryParseJson'),
}
